### PR TITLE
Set the default lib mesos location if it is null, as is the case befo…

### LINKED ISSUE #379: Upgrade framework fail for unable to find libmesos_location
Here is the exception when upgrade the framework from 1.0.20 to the latest one:
```
ERROR [2017-01-23 22:46:24,293] com.mesosphere.dcos.cassandra.common.config.DefaultConfigurationManager: Unable to fetch version: 8ea1d8b6-2f70-4160-b950-db1cfd277c18
! java.lang.NullPointerException: null
! at java.net.URI$Parser.parse(URI.java:3042) ~[na:1.8.0_112]
! at java.net.URI.<init>(URI.java:588) ~[na:1.8.0_112]
! at java.net.URI.create(URI.java:850) ~[na:1.8.0_112]
! at com.mesosphere.dcos.cassandra.common.config.ExecutorConfig.create(ExecutorConfig.java:76) ~[cassandra-commons-1.0.22-uber1-SNAPSHOT.jar:na]
! at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_112]
! at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_112]
! at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_112]
! at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_112]
! at com.fasterxml.jackson.databind.introspect.AnnotatedMethod.call(AnnotatedMethod.java:120) ~[jackson-databind-2.6.3.jar:2.6.3]
! at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromObjectWith(StdValueInstantiator.java:227) ~[jackson-databind-2.6.3.jar:2.6.3]
! ... 37 common frames omitted
! Causing: com.fasterxml.jackson.databind.JsonMappingException: Instantiation of [simple type, class com.mesosphere.dcos.cassandra.common.config.ExecutorConfig] 
```

It should be because libmesos_location doesn't exist in older framework. (https://github.com/mesosphere/dcos-cassandra-service/pull/338/files#diff-4e79cb08d78f17c29302ad1c91bdc031R12)

### PR DESCRIPTION
**Pull request by verma7**
…re upgrading the scheduler.

Fixes #379 .

### CODE REVIEW

**Comment by verma7** [comment]
Requesting a review from @NimaVaziri as the bug was introduced in #338.

File: cassandra-commons/src/main/java/com/mesosphere/dcos/cassandra/common/config/ExecutorConfig.java [hunk 1]
```diff
@@ -16,6 +17,8 @@
 
 public class ExecutorConfig {
 
+    public static final String DEFAULT_LIBMESOS_LOCATION = "http://downloads.mesosphere.com/libmesos-bundle/libmesos-bundle-1.8.7-1.0.2.tar.gz";
```
Comment (cooldoger) [inline cassandra-commons/src/main/java/com/mesosphere/dcos/cassandra/common/config/ExecutorConfig.java]: Could that be fetched from yaml file?

Comment (verma7) [inline cassandra-commons/src/main/java/com/mesosphere/dcos/cassandra/common/config/ExecutorConfig.java]: I don't see a way of doing that.

Comment (nickbp) [inline cassandra-commons/src/main/java/com/mesosphere/dcos/cassandra/common/config/ExecutorConfig.java]: this could default to the value of the `EXECUTOR_LIBMESOS_LOCATION` envvar

File: cassandra-commons/src/main/java/com/mesosphere/dcos/cassandra/common/config/ExecutorConfig.java [hunk 2]
```diff
@@ -62,6 +65,9 @@ public static ExecutorConfig create(
             @JsonProperty("cache_fetched_uris") boolean cacheFetchedUris)
             throws URISyntaxException, UnsupportedEncodingException {
 
+        if (libmesosLocation == null || StringUtils.isEmpty(libmesosLocation)) {
```
Comment (nickbp) [inline cassandra-commons/src/main/java/com/mesosphere/dcos/cassandra/common/config/ExecutorConfig.java]: `StringUtils.isEmpty()` already includes a `null` check, the `null` check here shouldn't be needed: https://commons.apache.org/proper/commons-lang/javadocs/api-2.6/org/apache/commons/lang/StringUtils.html#isEmpty(java.lang.String)

Comment (nickbp) [inline cassandra-commons/src/main/java/com/mesosphere/dcos/cassandra/common/config/ExecutorConfig.java]: Could have a comment here explaining that this check is for compatibility with upgrades from 1.0.22
